config:
  anomalyDetectorTypes:
    alwaysAnomalyV1:
      name: Always Anomaly anomaly detector
      enabled:
    consecutiveAnomalyV1:
      name: Consecutive anomaly detector
      enabled: false
    timeframeAnomalyV1:
      name: Timeframe anomaly detector
      enabled: false